version: "3"

services:
  app:
    build:
      context: .
    depends_on:
      - 'db'
    ports:
      - "80:80"
    volumes:
      - ./app:/app
      - ./scripts:/scripts

    env_file:
      - .env


  db:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080