# Generated by Django 3.2.9 on 2021-11-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211123_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='position',
            field=models.PositiveIntegerField(default=99999999),
        ),
    ]
