# Generated by Django 3.2.9 on 2021-11-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_postimage_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postimage',
            options={'ordering': ('-position',)},
        ),
        migrations.AddField(
            model_name='postimage',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
