# Generated by Django 3.2.9 on 2021-11-23 21:08

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20211123_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.safe_file_path),
        ),
        migrations.AddField(
            model_name='post',
            name='image_thumb',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to=core.models.safe_file_path),
        ),
    ]
