# Generated by Django 3.2.9 on 2021-11-23 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20211123_2208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomment',
            old_name='author',
            new_name='user',
        ),
    ]
