# Generated by Django 3.2.6 on 2023-01-19 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodlog',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
