# Generated by Django 3.2.6 on 2023-01-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_alter_moodlog_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodlog',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
