# Generated by Django 3.2.6 on 2023-01-23 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_alter_moodlog_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('has_value', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='activitylog',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logs.activity'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ActivityColour',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='custom_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logs.customactivity'),
        ),
    ]
