# Generated by Django 3.2.6 on 2023-03-03 16:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logs', '0009_alter_customactivity_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='CustomActivity',
            new_name='CustomUserActivity',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='mood_level',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitylog',
            name='notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
