# Generated by Django 3.2.6 on 2023-03-08 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0010_auto_20230303_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('inhale', models.SmallIntegerField()),
                ('hold', models.SmallIntegerField()),
                ('exhale', models.SmallIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='moodlog',
            name='level',
        ),
        migrations.AddField(
            model_name='moodlog',
            name='emotional_level',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='moodlog',
            name='happiness_level',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='moodlog',
            name='stress_level',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='MeditationCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.TimeField()),
                ('meditation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logs.meditation')),
                ('mood_after', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_after', to='logs.moodlog')),
                ('mood_before', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_before', to='logs.moodlog')),
            ],
        ),
    ]
