# Generated by Django 3.2.6 on 2023-03-08 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0011_auto_20230308_1407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moodlog',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='meditationcycle',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='moodlog',
            name='datetime',
        ),
        migrations.AddField(
            model_name='moodlog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 8, 14, 13, 23, 374650)),
        ),
    ]
