# Generated by Django 3.2.6 on 2023-03-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0012_auto_20230308_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
