# Generated by Django 3.2.6 on 2023-03-13 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0013_alter_moodlog_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreathingCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BreathingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('inhale', models.SmallIntegerField()),
                ('hold_inhale', models.SmallIntegerField()),
                ('exhale', models.SmallIntegerField()),
                ('hold_exhale', models.SmallIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='meditationcycle',
            name='meditation',
        ),
        migrations.RemoveField(
            model_name='meditationcycle',
            name='mood_after',
        ),
        migrations.RemoveField(
            model_name='meditationcycle',
            name='mood_before',
        ),
        migrations.DeleteModel(
            name='Meditation',
        ),
        migrations.DeleteModel(
            name='MeditationCycle',
        ),
        migrations.AddField(
            model_name='breathingcycle',
            name='breathing_exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logs.breathingexercise'),
        ),
        migrations.AddField(
            model_name='breathingcycle',
            name='mood_after',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_after', to='logs.moodlog'),
        ),
        migrations.AddField(
            model_name='breathingcycle',
            name='mood_before',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_before', to='logs.moodlog'),
        ),
    ]
