# Generated by Django 3.2.6 on 2023-03-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0014_auto_20230313_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='breathingexercise',
            name='descritption',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='breathingexercise',
            name='exhale_notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='breathingexercise',
            name='hold_exhale_notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='breathingexercise',
            name='hold_inhale_notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='breathingexercise',
            name='inhale_notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='breathingexercise',
            name='overview',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
