# Generated by Django 3.2.6 on 2023-03-13 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0016_rename_descritption_breathingexercise_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moodlog',
            old_name='emotional_level',
            new_name='anger',
        ),
        migrations.RenameField(
            model_name='moodlog',
            old_name='happiness_level',
            new_name='focus',
        ),
        migrations.RenameField(
            model_name='moodlog',
            old_name='stress_level',
            new_name='stress',
        ),
    ]
