# Generated by Django 3.2.6 on 2023-03-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0017_auto_20230313_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='breathingcycle',
            name='duration',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
