# Generated by Django 3.2.6 on 2023-03-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0018_breathingcycle_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='breathingcycle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
