# Generated by Django 3.2.6 on 2023-03-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0019_breathingcycle_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='breathingexercise',
            name='reference',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
