# Generated by Django 3.2.6 on 2023-05-02 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0020_breathingexercise_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='custom_activity',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customuseractivity',
            name='user',
        ),
        migrations.DeleteModel(
            name='SimpleActivity',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
        migrations.DeleteModel(
            name='CustomUserActivity',
        ),
    ]
