# Generated by Django 3.2.6 on 2023-01-23 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='activities',
        ),
    ]
