# Generated by Django 3.2.6 on 2023-05-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_totp_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', error_messages={'unique': 'A user with this email already exists'}, max_length=255, unique=True, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
